paths:
  /api/products/:
    post:
      summary: Agrega un producto (con rol de admin)
      tags:
        - Products
      parameters:
        - in: body
          name: product
          required: true
          description: nuevo producto
          schema:
            type: object
            properties:
              title:
                type: string
                description: titulo del producto
              description:
                type: string
                description: descripcion del producto
              code:
                type: string
                description: codigo unico de producto
              category:
                type: string
                description: categoria del producto
              brand:
                type: string
                description: marca del producto
              price:
                type: number
                description: precio del producto
              stock:
                type: integer
                description: stock disponible del producto
              thumbnails:
                type: array
                description: imagenes del producto
                items:
                  type: string
      responses:
        "200":
          description: Productos agregado correctamente
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: productos no encontrados
        "500":
          description: Error interno del servidor

    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Productos cargados correctamente
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: productos no encontrados
        "500":
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: parametro id del usuario
          schema:
            type: string
      responses:
        "200":
          description: producto encontrado correctamente
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: producto no encontrado
        "500":
          description: Error interno del servidor

    delete:
      summary: Borra un producto por id (con rol de admin)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: parametro id del usuario
          schema:
            type: string
      responses:
        "200":
          description: producto borrado correctamente
        "404":
          description: producto no encontrado
        "500":
          description: Error interno del servidor

    put:
      summary: Actualiza un producto por id (con rol de admin)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: parametro id del usuario
          schema:
            type: string
        - in: body
          name: product
          required: true
          description: nueva info del producto
          schema:
            type: object
            properties:
              title:
                type: string
                description: titulo del producto
              description:
                type: string
                description: descripcion del producto
              code:
                type: string
                description: codigo unico de producto
              category:
                type: string
                description: categoria del producto
              brand:
                type: string
                description: marca del producto
              price:
                type: number
                description: precio del producto
              stock:
                type: integer
                description: stock disponible del producto
              thumbnails:
                type: array
                description: imagenes del producto
                items:
                  type: string
      responses:
        "200":
          description: producto encontrado correctamente
        "404":
          description: producto no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: id autogenerado
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        code:
          type: string
          description: codigo unico de producto
        category:
          type: string
          description: categoria del producto
        brand:
          type: string
          description: marca del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: integer
          description: stock disponible del producto
        status:
          type: boolean
          description: estado del producto
        thumbnails:
          type: array
          description: imagenes del producto
          items:
            type: string
      example:
        _id: gdfs645643hjhbj6k5478k76j9bn
        title: Producto de prueba
        description: Descripcion de prueba
        code: abc234
        category: lavanderia
        brand: chevrolet
        price: 200
        stock: 10
        status: true
        thumbnails: ["fgsdfdfas"]
